### ISSUE TITLE
undefined symbol: g_task_get_source_tag

### ISSUE THREAD

**Issue by druckmusik** [gnunn1/tilix#1548]
Hello,

compiled tilix from master without problems,
but when trying to start, I get:

object.Exception@generated/gtkd/gtkd/Loader.d(125): Library load failed (libgdk-3.so.0): /usr/lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0: undefined symbol: g_task_get_source_tag

Am I missing something?

**Comment by gnunn1** [comment]
What commands are you using to build tilix?

**Comment by druckmusik** [comment]
./autogen.sh 
./configure --prefix=/usr
make
./tilix

**Comment by gnunn1** [comment]
Does it make any difference if you build it with dub:

```dub build --build=release --compiler-ldc2```

**Comment by druckmusik** [comment]
With  dub  it doesn't build at all. Maybe I'm missing something:

```
> dub build --build=release --compiler-ldc2
Unknown command line flags: --compiler-ldc2
Type "dub build -h" to get a list of all supported flags.
```

```
> dub build --build=release --compiler=ldc2
Performing "release" build using ldc2 for x86_64.
gtk-d:gtkd 3.8.3: building configuration "library"...
gtk-d:vte 3.8.3: building configuration "library"...
tilix ~master: building configuration "default"...
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/8/../../../x86_64-linux-gnu/libphobos2-ldc.a(zlib.o): in function `_D3std4zlib7adler32FkAxvZk':
(.text._D3std4zlib7adler32FkAxvZk[_D3std4zlib7adler32FkAxvZk]+0x50): undefined reference to `adler32'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/8/../../../x86_64-linux-gnu/libphobos2-ldc.a(zlib.o): in function `_D3std4zlib5crc32FkAxvZk':
(.text._D3std4zlib5crc32FkAxvZk[_D3std4zlib5crc32FkAxvZk]+0x50): undefined reference to `crc32'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/8/../../../x86_64-linux-gnu/libphobos2-ldc.a(zlib.o): in function `_D3std4zlib8compressFAxviZAh':
(.text._D3std4zlib8compressFAxviZAh[_D3std4zlib8compressFAxviZAh]+0x4c): undefined reference to `compress2'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/8/../../../x86_64-linux-gnu/libphobos2-ldc.a(zlib.o): in function `_D3std4zlib10uncompressFAxvmiZAv':
(.text._D3std4zlib10uncompressFAxvmiZAv[_D3std4zlib10uncompressFAxvmiZAv]+0xd1): undefined reference to `inflate'
/usr/bin/ld: (.text._D3std4zlib10uncompressFAxvmiZAv[_D3std4zlib10uncompressFAxvmiZAv]+0xe6): undefined reference to `inflateEnd'
/usr/bin/ld: (.text._D3std4zlib10uncompressFAxvmiZAv[_D3std4zlib10uncompressFAxvmiZAv]+0x164): undefined reference to `inflateEnd'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/8/../../../x86_64-linux-gnu/libphobos2-ldc.a(zlib.o): in function `_D3std4zlib8Compress5errorMFiZv':
(.text._D3std4zlib8Compress5errorMFiZv[_D3std4zlib8Compress5errorMFiZv]+0x16): undefined reference to `deflateEnd'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/8/../../../x86_64-linux-gnu/libphobos2-ldc.a(zlib.o): in function `_D3std4zlib8Compress6__dtorMFZv':
(.text._D3std4zlib8Compress6__dtorMFZv[_D3std4zlib8Compress6__dtorMFZv]+0x18): undefined reference to `deflateEnd'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/8/../../../x86_64-linux-gnu/libphobos2-ldc.a(zlib.o): in function `_D3std4zlib8Compress8compressMFAxvZQe':
(.text._D3std4zlib8Compress8compressMFAxvZQe[_D3std4zlib8Compress8compressMFAxvZQe]+0xd1): undefined reference to `deflate'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/8/../../../x86_64-linux-gnu/libphobos2-ldc.a(zlib.o): in function `_D3std4zlib8Compress5flushMFiZAv':
(.text._D3std4zlib8Compress5flushMFiZAv[_D3std4zlib8Compress5flushMFiZAv]+0x84): undefined reference to `deflate'
/usr/bin/ld: (.text._D3std4zlib8Compress5flushMFiZAv[_D3std4zlib8Compress5flushMFiZAv]+0xe1): undefined reference to `deflate'
/usr/bin/ld: (.text._D3std4zlib8Compress5flushMFiZAv[_D3std4zlib8Compress5flushMFiZAv]+0x12a): undefined reference to `deflateEnd'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/8/../../../x86_64-linux-gnu/libphobos2-ldc.a(zlib.o): in function `_D3std4zlib10UnCompress5errorMFiZv':
(.text._D3std4zlib10UnCompress5errorMFiZv[_D3std4zlib10UnCompress5errorMFiZv]+0x16): undefined reference to `inflateEnd'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/8/../../../x86_64-linux-gnu/libphobos2-ldc.a(zlib.o): in function `_D3std4zlib10UnCompress6__dtorMFZv':
(.text._D3std4zlib10UnCompress6__dtorMFZv[_D3std4zlib10UnCompress6__dtorMFZv]+0x1c): undefined reference to `inflateEnd'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/8/../../../x86_64-linux-gnu/libphobos2-ldc.a(zlib.o): in function `_D3std4zlib10UnCompress10uncompressMFAxvZQe':
(.text._D3std4zlib10UnCompress10uncompressMFAxvZQe[_D3std4zlib10UnCompress10uncompressMFAxvZQe]+0xbd): undefined reference to `inflate'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/8/../../../x86_64-linux-gnu/libphobos2-ldc.a(zlib.o): in function `deflateInit':
(.text.deflateInit[deflateInit]+0xd): undefined reference to `deflateInit_'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/8/../../../x86_64-linux-gnu/libphobos2-ldc.a(zlib.o): in function `inflateInit':
(.text.inflateInit[inflateInit]+0xd): undefined reference to `inflateInit_'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/8/../../../x86_64-linux-gnu/libphobos2-ldc.a(zlib.o): in function `deflateInit2':
(.text.deflateInit2[deflateInit2]+0xc): undefined reference to `deflateInit2_'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/8/../../../x86_64-linux-gnu/libphobos2-ldc.a(zlib.o): in function `inflateInit2':
(.text.inflateInit2[inflateInit2]+0xd): undefined reference to `inflateInit2_'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/8/../../../x86_64-linux-gnu/libphobos2-ldc.a(zlib.o): in function `inflateBackInit':
(.text.inflateBackInit[inflateBackInit]+0xe): undefined reference to `inflateBackInit_'
collect2: error: ld returned 1 exit status
Error: /usr/bin/gcc failed with status: 1
ldc2 failed with exit code 1.
```

**Comment by gnunn1** [comment]
What version of ldc2 are you using? I'm on 1.11.0

**Comment by druckmusik** [comment]
```
> ldc2 --version
LDC - the LLVM D compiler (1.11.0):
  based on DMD v2.081.2 and LLVM 6.0.1
  built with LDC - the LLVM D compiler (0.17.6)
  Default target: x86_64-pc-linux-gnu
  Host CPU: ivybridge
```

**Comment by gnunn1** [comment]
Any chance you are on Arch? There was an issue with libphobos there that has been corrected.

Otherwise I don't know what the issue is, sorry.

**Comment by druckmusik** [comment]
I'm on debian buster/sid
Tried the latest mayter today, but still the same problem :-(
