### ISSUE TITLE
Cannot set shortcut <ctrl><tab> for "Switch to Next Session" in some environments

### ISSUE THREAD

**Issue by soapergem** [gnunn1/tilix#1913]
Since #1487 was so hastily closed without investigation, I'm opening a new issue. Multiple people have confirmed that this is still a problem on versions as late as 1.9.1 when running in Ubuntu. Personally I can confirm that on Ubuntu 20.04 I have Tilix 1.9.1 installed from the webupd8team/terminix PPA. When I run `tilix --version` I see this:

```
Versions
	Tilix version: 1.9.1
	VTE version: 0.60
	GTK Version: 3.24.18

Tilix Special Features
	Notifications enabled=0
	Triggers enabled=0
	Badges enabled=1
```

When trying to set the "Switch to Next Session" keyboard shortcut to <ctrl><tab>, it doesn't work. Here are my same steps to reproduce from the other issue:

* Go into Preferences > Shortcuts
* Double-click on the shortcut key corresponding to "Switch to next session"
* Try to enter Ctrl+Tab

It won't work because the Ubuntu system itself (Gnome? X11? Something else?) seems to capture that input before Tilix does, and interprets it as input that is trying to to do something invalid with the windows, because you hear a generic system alert sound - the same kind of sound which normally indicates "you can't do that."

**Comment by garrettgibo** [comment]
The shortcuts are explicitly defined in `data/gsettings/com.gexperts.Tilix.gschema.xml`, with the "Switch to Next session" shortcut being defined at:

https://github.com/gnunn1/tilix/blob/e202a3c47ef389c663f86c708c05e7feaf56ae3b/data/gsettings/com.gexperts.Tilix.gschema.xml#L1101-L1108

In some light testing I've been able to get the ctrl-tab and ctrl-shift-tab shortcuts to work by just manually changing the file.

**Comment by mojason-81** [comment]
I'm having this exact same issue.
Pop!_OS 20.04
Tilix 1.9.1

Seems like a really old bug.  Would be nice if this were fixed.

**Comment by sangwoo-joh** [comment]
I'm still having this issue on Tilix 1.9.1 on my Ubuntu Budgie 20.04!

**Comment by ronny-rentner** [comment]
I have the same issue. So +1 for fixing it :)
